---
- name: Setup environment for the project
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache and install packages
      apt:
        name:
          - git
          - docker.io
          - openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: yes
